---
title: "Evaluating GPT-3 fine-tune"
author: "Anton Drasbæk & Mina Almasi"
date: "10/7/2022"
output: html_document
---
# Description
This file covers how we evaluated our GPT-3 fine-tune. It includes the plot of the training loss.

# Load Packages and Data
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
pacman::p_load(tidyverse, ggthemes)
```

import data
```{r}
data <- read_csv(file.path("results", "gpt3_finetune_results.csv"))
data["model"] <- "samf2" # arbitrary name 
```

# Plotting
Training loss
```{r}
training_loss_plot <- ggplot(data, aes(x = elapsed_examples, y = training_loss)) +
  labs(y = "Training Loss", x="Elapsed Examples") +
  guides(color="none")+
  geom_vline(xintercept = 1209, alpha = 1,  size = 0.8, linetype = "dashed") +
  geom_vline(xintercept = 1209*2, alpha = 1,  size = 0.8, linetype = "dashed") +
  geom_vline(xintercept = 1209*3, alpha = 1,  size = 0.8, linetype = "dashed") +
  geom_vline(xintercept = 1209*4, alpha = 1,  size = 0.8, linetype = "dashed") +
  scale_y_continuous(breaks = c(0.5, 0.6, 0.7, 0.8, 0.9, 1.0))+
  geom_smooth(color = "#808080", size = 3) +
  theme(text = element_text(family = "Times New Roman"),
        plot.margin = margin(0.5,0.5,0.75,0.75, "cm"),
        axis.title.x = element_text( size = 22, vjust = -2, face = "bold"), 
        axis.title.y = element_text( size = 22, vjust = 2, face = "bold"), 
        panel.background = element_blank(), 
        axis.line = element_line(),
        axis.text.x = element_text(size = 20),
        axis.text.y = element_text(size = 20),
        axis.ticks = element_line( size = 1),
        axis.ticks.length=unit(.125, "cm"),
        axis.text = element_text(size = 12)
        ) 

training_loss_plot
```


```{r}
filename = 
ggsave(training_loss_plot, filename = file.path("plots", "training_loss_finetuning_gpt3.png"), dpi = 600, type = "cairo", width = 10, height = 6, units = "in")
```

Training accuracy
```{r}
training_acc_plot <- ggplot(data, aes(x = elapsed_examples, y = training_token_accuracy)) +
  geom_smooth(color = "#E14D50", size = 2) +
  labs(title = "Training Accuracy for GPT-3 Fine-Tuning", y = expression(paste(bold("Training Token Accuracy"))), x=(expression(paste(bold("Elapsed Examples"))))) +
  guides(color="none")+
  geom_vline(xintercept = 1209, alpha = 1, color = "black", size = 1, linetype = "dashed") +
  geom_vline(xintercept = 1209*2, alpha = 1, color = "black", size = 1, linetype = "dashed") +
  geom_vline(xintercept = 1209*3, alpha = 1, color = "black", size = 1, linetype = "dashed") +
  geom_vline(xintercept = 1209*4, alpha = 1, color = "black", size = 1, linetype = "dashed") + 
  theme_few(base_family = "Times New Roman", base_size = 16)+ 
  theme(plot.title = element_text(hjust = 0.5, size = 18, face = "bold"))

training_acc_plot
```

